# Generated by Django 5.1.4 on 2025-01-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
    ]
